services:
  - type: web
    name: innovasoft-app
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: MONGO_URL
        value: mongodb://admin:securepassword@mongodb:27017
      - key: DATABASE_NAME
        value: innovasoft_db
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
  - type: pserv
    name: innovasoft-mongodb
    plan: free
    region: oregon